version: '3.8' 
 
volumes: 
  postgres_data: 
  static_volume: 
 
 
services: 
 
  db: 
    image: postgres:latest 
    volumes: 
      - postgres_data:/var/lib/postgresql/data/ 
    env_file: 
      - ./api_yamdb/.env 
 
  web: 
    build: .
    restart: always 
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000 
    volumes:
      - static_volume:/home/netsh/dev/yamdb_final/static
    ports: 
      - "8000:8000" 
    depends_on: 
      - db 
    env_file: 
      - ./api_yamdb/.env 
    environment: 
      - POSTGRES_USER=netshy 
      - POSTGRES_PASSWORD=netshy 

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/netsh/dev/yamdb_final/static
    ports:
      - 1337:80
    depends_on:
      - web
